replicaCount: 1
image:
  repository: ipaasvertigo/devportal
  tag: 0.2.0
  pullPolicy: IfNotPresent
#imagePullSecrets:
nodeEnv: development
service:
  name: devportal
  type: ClusterIP
  containerPort: 7007
ingress:
  enabled: false
  tls: false
  ingressClassName: "kong"
  annotations: {}
  hosts:
    - host:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devportal
              port:
                number: 80
#resources:
  #requests:
    #memory: 512Mi
  #limits:
    #memory: 1024Mi
appConfig:
  app:
    baseUrl: 
  backend:
    baseUrl: 
auth:
  okta:
    clientId: 
    clientSecret: 
    audience: 
githubToken: 
githubSpecHouseURL: 
