replicas: 1
image:
  repository: veecode/devportal
  tag: bundle
  pullPolicy: IfNotPresent
#imagePullSecrets:
environment: development

service:
  enabled: true
  type: ClusterIP
  containerPort: 7007

ingress:
  enabled: false
  annotations: {}
  tls: {}

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1024Mi
    cpu: 500m

appConfig:
  title: Devportal
  app:
    baseUrl: http://localhost:3000
  backend:
    baseUrl: http://localhost:7007
    secret: djaskldhaskljdaskljdsklajs
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      database: platform_devportal
      user: postgres
      password: postgres

grafana:
  enabled: false

argocd:
  enabled: false

vault:
  enabled: false

kong:
  enabled: false

okta: {}
auth: {}

integrations: {}

catalog:
  providers: {}

platform:
  guest:
    enabled: true
  apiManagement:
    enabled: false
    readOnlyMode: false

kubernetes: {}
