replicaCount: 1
image:
  repository: 
  tag: 1.0.5
  pullPolicy: IfNotPresent
imagePullSecrets:
nodeEnv: development
service:
  name: devportal
  type: ClusterIP
  containerPort: 7007
resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1024Mi
appConfig:
  app:
    baseUrl: 
  backend:
    baseUrl: 
auth:
  okta:
    clientId: 
    clientSecret: 
    audience: 
githubToken: 
githubSpecHouseURL: 
