apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devportal-charts.fullname" . }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: devportal
  template:
    metadata:
      labels:
        app: devportal
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/devportal_configmap.yaml") . | sha256sum }}        
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          {{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "devportal-charts.fullname" . }}-credentials
            - configMapRef:
                name: {{ include "devportal-charts.fullname" . }}-app-env
          env:
            - name: NODE_ENV
              value: {{ .Values.environment | default "development" }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
          - name: app-config
            mountPath: /app/app-config.yaml
            subPath: app-config

          readinessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
              initialDelaySeconds: 60
              periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 7007
              path: /healthcheck
              initialDelaySeconds: 90
              periodSeconds: 10
      volumes:
        - name: app-config
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: "{{ include "devportal-charts.fullname" . }}-app-env"
