{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: vkpr
    {{- $selectors := .Values.serviceMonitor.selectors }}
    {{- if $selectors }}
    {{- toYaml $selectors | nindent 4 }}
    {{- else }}
    release: prometheus
    {{- end }}
spec:
  endpoints:
    - targetPort: 7007
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      operated-prometheus: "true"
{{- end }}