apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devportal-charts.fullname" . }}-credentials
type: Opaque
stringData:
  {{- if (and .Values.auth.providers.keycloak .Values.auth.providers.keycloak.metadataUrl) }}
  KEYCLOAK_METADATA_URL: {{ .Values.auth.providers.keycloak.metadataUrl }}
  {{- end }}
  {{- if (and .Values.auth.providers.keycloak .Values.auth.providers.keycloak.clientId) }}
  KEYCLOAK_CLIENT_ID: {{ .Values.auth.providers.keycloak.clientId }}
  {{- end }}
  {{- if (and .Values.auth.providers.keycloak .Values.auth.providers.keycloak.clientSecret) }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.auth.providers.keycloak.clientSecret }}
  {{- end }}
  {{- if (and .Values.appConfig.backend .Values.appConfig.backend.secret) }}
  BACKEND_AUTH_SECRET_KEY: {{ .Values.appConfig.backend.secret }}
  AUTH_USER_SESSION_SECRET: {{ .Values.appConfig.backend.secret }}
  {{- end }}
  {{- if (and .Values.appConfig.database.connection .Values.appConfig.database.connection.host) }}
  DATABASE_HOST: {{ .Values.appConfig.database.connection.host }}
  {{- end }}
  {{- if (and .Values.appConfig.database.connection .Values.appConfig.database.connection.database) }}
  DATABASE_NAME: {{ .Values.appConfig.database.connection.database }}
  {{- end }}
  {{- if (and .Values.appConfig.database.connection .Values.appConfig.database.connection.user) }}
  DATABASE_USER: {{ .Values.appConfig.database.connection.user }}
  {{- end }}
  {{- if (and .Values.appConfig.database.connection .Values.appConfig.database.connection.password) }}
  DATABASE_PASSWORD: {{ .Values.appConfig.database.connection.password }}
  {{- end }}
  {{- if (and .Values.grafana .Values.grafana.domain) }}
  GRAFANA_DOMAIN: {{ .Values.grafana.domain }}
  {{- end }}
  {{- if (and .Values.grafana .Values.grafana.token) }}
  GRAFANA_TOKEN: {{ .Values.grafana.token }}
  {{- end }}
  {{- if (and .Values.argocd .Values.argocd.domain) }}
  ARGOCD_DOMAIN: "{{ .Values.argocd.domain }}"
  ARGOCD_URL_API: "{{ .Values.argocd.domain }}/api/v1"
  {{- end }}
  {{- if (and .Values.argocd .Values.argocd.username) }}
  ARGOCD_USER: {{ .Values.argocd.username }}
  {{- end }}
  {{- if (and .Values.argocd .Values.argocd.token) }}
  ARGOCD_TOKEN: "{{ .Values.argocd.token }}"
  {{- end }}
    {{- if (and .Values.argocd .Values.argocd.authToken) }}
  ARGOCD_AUTH_TOKEN: "{{ .Values.argocd.authToken }}"
  {{- end }}
  {{- if (and .Values.vault .Values.vault.domain) }}
  VAULT_BASE_URL: {{ .Values.vault.domain }}
  {{- end }}
  {{- if (and .Values.vault .Values.vault.token) }}
  VAULT_TOKEN_RENEWABLE: {{ .Values.vault.token }}
  {{- end }}
  {{- if (and .Values.vault .Values.vault.secretEngine) }}
  VAULT_SECRET_ENGINE: {{ .Values.vault.secretEngine | default "secrets" }}
  {{- end }}
  {{- if (and .Values.kong .Values.kong.apiManager) }}
  KONG_API_MANAGER_HOST: {{ .Values.kong.apiManager }}
  {{- end }}
  {{- if (and .Values.kong .Values.kong.adminToken) }}
  KONG_ADMIN_TOKEN: {{ .Values.kong.adminToken }}
  {{- end }}
  {{- if (and .Values.okta .Values.okta.domain) }}
  OKTA_HOST: {{ .Values.okta.domain }}
  {{- end }}
  {{- if (and .Values.okta .Values.okta.token) }}
  OKTA_TOKEN: {{ .Values.okta.token }}
  {{- end }}
  {{- if (and .Values.catalog.providers.github .Values.catalog.providers.github.organization) }}
  CATALOG_GITHUB_ORGANIZATION: {{ .Values.catalog.providers.github.organization }}
  {{- end }}
  {{- if (and .Values.catalog.providers.github .Values.catalog.providers.github.catalogPath) }}
  CATALOG_GITHUB_CATALOG_PATH: {{ .Values.catalog.providers.github.catalogPath }}
  {{- end }}
  {{- if (and .Values.integrations.github .Values.integrations.github.token) }}
  GITHUB_TOKEN_SECRET: {{ .Values.integrations.github.token }}
  {{- end }}
  {{- if (and .Values.kubernetes .Values.kubernetes.serviceAccountToken) }}
  KUBERNETES_SERVICE_ACCOUNT_TOKEN: {{ .Values.kubernetes.serviceAccountToken }}
  {{- end }}
  {{- if (and .Values.kubernetes .Values.kubernetes.caData) }}
  KUBERNETES_CERTIFICATE_DATA: {{ .Values.kubernetes.caData }}
  {{- end }}
  {{- if (and .Values.auth.providers.github .Values.auth.providers.github.clientId) }}
  AUTH_GITHUB_CLIENT_ID: {{ .Values.auth.providers.github.clientId }}
  {{- end }}
  {{- if (and .Values.auth.providers.github .Values.auth.providers.github.clientSecret) }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.providers.github.clientSecret }}
  {{- end }}
