{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devportal-charts.fullname" . }}
  {{- if or ( and .Values.ingress.tls .Values.ingress.tls.secretName ) .Values.ingress.annotations }}
  annotations:
    {{- if and .Values.ingress.tls .Values.ingress.tls.secretName }}
    cert-manager.io/cluster-issuer: certmanager-issuer
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4}}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  {{- if and .Values.ingress.tls .Values.ingress.tls.secretName }}
  tls:
  - secretName: {{ .Values.ingress.tls.secretName }}
    hosts:
    - {{ .Values.ingress.host }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: "{{- include "devportal-charts.fullname" . }}"
                port:
                  number: {{ .Values.service.containerPort}}
 
{{- end }}
