{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{- include "devportal-charts.fullname" . }}"
  {{- if not .Values.ingress.enabled | default false }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: {{ include "devportal-charts.fullname" . }}
  type: {{ .Values.service.type }}   
{{- end }}