{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: devportal-prod
  {{- if not .Values.ingress.enabled -}}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: devportal-prod
  type: {{ .Values.service.type }}   
{{- end }}