apiVersion: v1
kind: Secret
metadata:
  name: platform-devportal-secret
  namespace: vkpr
  annotations:
    kubernetes.io/service-account.name: platform-devportal
type: kubernetes.io/service-account-token