name: Packer AMI Builder

on:
  workflow_dispatch:
    inputs:
      devportal_chart_version:
        description: 'Devportal chart version'
      admin_ui_chart_version:
        description: 'Admin UI chart version'
      
env:
  PACKER_VERSION: "1.10.1"
  AWS_ROLE_ARN: "arn:aws:iam::829720130733:role/Github_Action_IDP"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Checking version
      run: |
        if [ -z "${{ github.event.inputs.admin_ui_chart_version }}" ]; then
        ADMIN_UI_VERSION=$(curl -s https://artifacthub.io/api/v1/packages/helm/veecode-platform/devportal-admin-ui | jq -r '.available_versions | max | .version')
          
        else
          if [ curl -s https://artifacthub.io/api/v1/packages/helm/veecode-platform/devportal | jq -r "any(.available_versions[]; .version==\"${{ github.event.inputs.admin_ui_chart_version }}\")" ]; then
            ADMIN_UI_VERSION=${{ github.event.inputs.admin_ui_chart_version }}
          else 
            echo "Admin UI Version ${{ github.event.inputs.admin_ui_chart_version }} not found."
            exit 1;
          fi
        fi

        if [ -z "${{ github.event.inputs.devportal_chart_version }}" ]; then
          DEVPORTAL_VERSION=$(curl -s https://artifacthub.io/api/v1/packages/helm/veecode-platform/devportal | jq -r '.available_versions | max | .version')
        else
          if [ curl -s https://artifacthub.io/api/v1/packages/helm/veecode-platform/devportal | jq -r "any(.available_versions[]; .version==\"${{ github.event.inputs.devportal_chart_version }}\")" ]; then
            DEVPORTAL_VERSION=${{ github.event.inputs.devportal_chart_version }}
          else 
            echo "Devportal Version ${{ github.event.inputs.devportal_chart_version }} not found."
            exit 1;
          fi
        fi
        echo "ADMIN_UI_VERSION=$(echo $ADMIN_UI_VERSION)" >> $GITHUB_ENV
        echo "DEVPORTAL_VERSION=$(echo $DEVPORTAL_VERSION)" >> $GITHUB_ENV
    
    - name: print
      run: |
        echo "ADMIN_UI_VERSION: ${{ env.ADMIN_UI_VERSION }}"
        echo "DEVPORTAL_VERSION: ${{ env.DEVPORTAL_VERSION }}"