name: Packer AMI Builder

on:
  workflow_dispatch:
    inputs:
      devportal_chart_version:
        description: 'Devportal chart version'
      admin_ui_chart_version:
        description: 'Admin UI chart version'
      
env:
  PACKER_VERSION: "1.10.1"
  AWS_ROLE_ARN: "arn:aws:iam::829720130733:role/Github_Action_IDP"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: asdf
      run: |
        #check if github.event.inputs.admin_ui_chart_version is null or empty
        if [ -z "${{ github.event.inputs.admin_ui_chart_version }}" ]; then
        ADMIN_UI_VERSION=$(curl -s https://artifacthub.io/api/v1/packages/helm/veecode-platform/devportal-admin-ui | jq -r '.available_versions | max | .version')
          
        else
        ADMIN_UI_VERSION=${{ github.event.inputs.admin_ui_chart_version }}
        fi

        if [ -z "${{ github.event.inputs.devportal_chart_version }}" ]; then
        DEVPORTAL_VERSION=$(curl -s https://artifacthub.io/api/v1/packages/helm/veecode-platform/devportal | jq -r '.available_versions | max | .version')
          
        else
        DEVPORTAL_VERSION=${{ github.event.inputs.devportal_chart_version }}
        fi
        echo "ADMIN_UI_VERSION=$(cat $ADMIN_UI_VERSION)" >> $GITHUB_ENV
        echo "DEVPORTAL_VERSION=$(cat $DEVPORTAL_VERSION)" >> $GITHUB_ENV
    
    - name: print
      run: |
        echo "ADMIN_UI_VERSION: ${{ env.ADMIN_UI_VERSION }}"
        echo "DEVPORTAL_VERSION: ${{ env.DEVPORTAL_VERSION }}"