name: Publish Devportal Docker/Helm Chart

on:
  push:
    branches: ["main"]

jobs:
  #Getting requided versions for next steps
  requirements:
    runs-on: [self-hosted, macOS, ARM64]
    outputs:
      app_version: ${{ env.app_version }}
      chart_version: ${{ env.chart_version }}
      node_version: ${{ env.node_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Getting versions
        run: |
          echo "app_version=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          echo "chart_version=$(yq e '.version' chart/Chart.yaml)" >> $GITHUB_ENV
          echo "node_version=$(cat .nvmrc | grep -o '[0-9]*')" >> $GITHUB_ENV

  #parallel build for x64 and amr64
  buildDevportal:
    needs: [requirements]
    strategy:
      matrix:
        os: [ubuntu-latest, [self-hosted, macOS, ARM64]]
    runs-on: ${{ matrix.os }}
    env:
      NODE_VERSION: ${{ needs.requirements.outputs.node_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: yarn
      
      - name: Getting arch
        run: echo "ARCH=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Building Devportal${{ runner.arch }}
        run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn build
      
      - name: Setup keychain
        if: runner.os == 'macOS'
        run: security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to Docker Hub
        run: |
          docker build . -t veecode/devportal-bundle-${{env.ARCH}}:${{ needs.requirements.outputs.app_version }} -f packages/backend/Dockerfile
          docker tag veecode/devportal-bundle-${{env.ARCH}}:${{ needs.requirements.outputs.app_version }} veecode/devportal-bundle-${{env.ARCH}}:latest
          docker push veecode/devportal-bundle-${{env.ARCH}}:${{ needs.requirements.outputs.app_version }}
          docker push veecode/devportal-bundle-${{env.ARCH}}:latest
 
  publishManifestDocker:
    needs: [requirements, buildDevportal]
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup keychain
        if: runner.os == 'macOS'
        run: security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }}      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Create/Publish version ${{ needs.requirements.outputs.app_version }} manifest
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
            inputs: veecode/devportal-bundle:${{ needs.requirements.outputs.app_version }}
            images: veecode/devportal-bundle-arm64:${{ needs.requirements.outputs.app_version }},veecode/devportal-bundle-x64:${{ needs.requirements.outputs.app_version }}
            amend: true
            push: true

      - name: Create/Publish version latest manifest
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
            inputs: veecode/devportal-bundle:latest
            images: veecode/devportal-bundle-arm64:latest,veecode/devportal-bundle-x64:latest
            amend: true
            push: true

  publishing:
    needs: [requirements, buildDevportal]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup helm
        uses: azure/setup-helm@v3

      - name: Installing frigate
        run:  pip install frigate
      
      - name: Generating Helm Documentation
        run: bash chart/generate-docs.sh
      
      - name: Check if chart docs have been generated as expected.
        run: |
          bash chart/generate-docs.sh
          if [ ! -f "./chart/README.md" ]; then
            echo "Error: chart/README.md does not exist."
            exit 1
          fi
          echo "chart/README.md created."

      - name: Build Helm Package
        run: |
          yq e '.image.repository = "veecode/devportal-bundle" ' -i chart/values.yaml
          yq e '.image.tag = "${{ needs.requirements.outputs.app_version }}" ' -i chart/values.yaml
          yq e '.appVersion= "${{ needs.requirements.outputs.app_version }}" ' -i chart/Chart.yaml
          mkdir -p charts
          helm package --sign --key 'Veecode Platform' --passphrase-file ./chart/passphrase --keyring ./chart/certificate.gpg chart --destination charts/

      - name: Publish Helm Charts
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "charts/"
          destination_repo: "veecode-platform/public-charts"
          destination_branch: "main"
          user_email: 'veecode-bot@vee.codes'
          user_name: 'veecode-bot'
          commit_message: "Publish new version devportal-${{ needs.requirements.outputs.chart_version }}"
      
      - name: Prepare doc references
        run: |
          mkdir -p tmpDocs/devportal
          cp packages/app/public/theme.json tmpDocs/devportal/
          cp keycloak/realm-platform-devportal.json tmpDocs/devportal/
        
      - name: Publishing doc references
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "tmpDocs/devportal/"
          destination_repo: "${{ github.repository_owner }}/support"
          destination_branch: "gh-pages"
          destination_folder: "references"
          user_email: 'veecode-bot@vee.codes'
          user_name: 'veecode-bot'
          commit_message: "Update devportal docs reference"
