name: Publish Devportal Homolog Helm Chart on apr Enviroment 

# on:
#   push:
#     branches: ["develop"]
on: 
  workflow_dispatch:
    
jobs:
   Install_Devportal_Homolog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Install Helm 
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install yq 
        shell: bash
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
          yq --version

      - name: Helm update chart
        shell: bash
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
          yq e ".image.tag = \"$(jq -r .version package.json)\"" -i ./chart/values.yaml
          yq e ".appVersion = \"$(jq -r .version package.json)\"" -i ./chart/Chart.yaml

          if helm ls -A | grep -q "platform-devportal-homolog"; then
            NAMESPACE=$(helm ls -A | grep platform-devportal-homolog | awk -F' ' '{print $2}')
            helm get values platform-devportal-homolog -n $NAMESPACE | tail -n +2 > devportal.yaml
            helm upgrade platform-devportal-homolog --install --recreate-pods --values ./devportal.yaml ./chart -n $NAMESPACE
          else 
            echo "Installation of Platform devportal (Homolog) not found on ${{ secrets.CLUSTER_NAME }}"
            exit 1
          fi